system:
  code: EUIS
spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:oracle:thin:@//172.26.1.98:7621/DPDPS
    password: EUIS
    username: EUIS
mybatis:
  mapper-locations: classpath:mapper/*.xml
security:
#  allow-origins: ${euisv.server},${euisb.server},${euisbq.server},http://localhost:8877
#  allow-methods: GET,POST,PUT,DELETE
#  allow-headers: Content-Type,Authorization,SSO-TOKEN,X-XSRF-TOKEN
#  jwt-verify-url: jwt-verify-url
  token-expire-time: 1800
euisv:
  server: http://localhost:9999
  context-path: /front
euisb:
  server: http://localhost:8888
  context-path: /euisb
euisbq:
  server: http://localhost:8787
  context-path: /euisbq
cas:
  server: cas server
  logout: ${cas.server}/logout?service=${euisv.server}${euisv.context-path}
logging:
  level:
    org:
      springframework:
        security: trace